name: CI
on:
  push:
    branches:
      - react
    paths-ignore:
      - '**.md'
      - '**.xlsx'
      - '**.json'
      - '**.csv'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install modules
        run: npm ci
      - name: Build Client
        run: npm run build
      - name: Build Server and Quick smoke test
        # https://github.com/npm/npx/issues/36#issuecomment-659944817
        run: npx --shell sh ts-node src/server/index.ts --test
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install modules
        run: npm ci
      - name: Run lints
        run: npm run lint
      - name: Run tests
        # TODO all tests
        run: npx jest --ci --runInBand imports.test.ts parsePdf.test.ts
